import * as React from 'react'
import type { Metadata } from 'next'
import Container from '@mui/material/Container'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import ThemeRegistry from '@/theme/ThemeRegistry'

const sections = [
  { title: 'Мыйзамдар архиви', url: '#' },
  { title: 'Мыйзам сунуштоо', url: '#' },
]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <Container maxWidth="lg">
            <Header title="Мыйзам долбоору" sections={sections} />
            {children}
          </Container>
          <Footer
            title="Footer"
            description="Something here to give the footer a purpose!"
          />
        </body>
      </ThemeRegistry>
    </html>
  )
}
