import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import * as React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import Container from "@mui/material/Container";
import { ThemeProvider } from "@mui/material/styles";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { theme } from "@/theme";

const inter = Inter({ subsets: ["latin"] });

const sections = [
  { title: "Мыйзамдар архиви", url: "#" },
  { title: "Мыйзам сунуштоо", url: "#" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Container maxWidth="lg">
            <Header title="Мыйзам долбоору" sections={sections} />
            {children}
          </Container>
          <Footer
            title="Footer"
            description="Something here to give the footer a purpose!"
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
